name: Build and run main.go

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  execute-main-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Build main.go
        run: go build -o main main.go
      
      - name: Run main.go 1 times
        run: |
          for i in {1..1}; do
            echo "Run #$i"
            ./main
          done